#!/bin/bash
# Stage the CMS open data and the theory priors on UCI HPC3.
#
# RUN INSIDE AN INTERACTIVE COMPUTE NODE. The 2.2 GB CMS file is a bulk
# download, and the HPC3 acceptable-use policy forbids "downloads of packages,
# data, large files that exceed a few Gbs" on login nodes:
#   https://rcic.uci.edu/account/acceptable-use.html
#
#   ssh <UCInetID>@hpc3.rcic.uci.edu
#   srun -c 4 -p free --mem=8G --time=02:00:00 --pty /bin/bash -i
#   cd /pub/$USER/otus && bash deploy/hpc3/stage_data.sh
#
# What the joint training path reads (source-verified from
# outputs/cms_Joint/Run_H/config.resolved.json and configs_joint/cms_Joint_runA.yaml):
#
#   data/Run2012BC_DoubleMuParked_Muons.root                     both regions (CMS data)
#   data/legacy/cms_jpsi_mumu_mg5_8tev_mixed_ptj5.hdf5           jpsi theory prior
#   data/cms_dymumu_mg5py8_ckkwl_8tev_inclusive_0j1j_fiducial_70_110_1M.hdf5   z theory prior
#
# The A2 / D3 / unified-prior arms additionally read data/legacy/priors/*.hdf5.
# Neither data/ nor those files are in git (.gitignore line 11), so they must
# be copied from the workstation or regenerated; see the runbook section 4.

set -euo pipefail

REPO_ROOT="${OTUS_REPO:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)}"
DATA_ROOT="${OTUS_DATA_ROOT:-${REPO_ROOT}/data}"
ROOT_NAME="Run2012BC_DoubleMuParked_Muons.root"
ROOT_URL="https://opendata.cern.ch/record/12341/files/${ROOT_NAME}"
# CERN Open Data record 12341, DOI 10.7483/OPENDATA.CMS.LVG5.QT81 (CC0-1.0).
ROOT_BYTES=2244449133
ROOT_ADLER32=1fa61aca

echo "host      : $(hostname)"
echo "data root : ${DATA_ROOT}"
echo

if [[ "$(hostname)" == login-* ]]; then
    echo "ERROR: this is a login node. Re-run inside an interactive compute node." >&2
    exit 1
fi

mkdir -p "${DATA_ROOT}/legacy/priors"

# ---------------------------------------------------------------- CMS data --
target="${DATA_ROOT}/${ROOT_NAME}"
if [[ -f "${target}" ]] && [[ "$(stat -c %s "${target}")" == "${ROOT_BYTES}" ]]; then
    echo "==> ${ROOT_NAME} already present with the expected size"
else
    echo "==> downloading ${ROOT_NAME} (2.1 GiB) from CERN Open Data"
    curl -L --fail --retry 3 --retry-delay 10 -o "${target}.part" "${ROOT_URL}"
    mv "${target}.part" "${target}"
fi

actual_bytes=$(stat -c %s "${target}")
if [[ "${actual_bytes}" != "${ROOT_BYTES}" ]]; then
    echo "ERROR: ${target} is ${actual_bytes} bytes, expected ${ROOT_BYTES}" >&2
    exit 1
fi

echo "==> verifying the CERN adler32 checksum"
python - "${target}" "${ROOT_ADLER32}" <<'PY'
import sys
import zlib

path, expected = sys.argv[1], sys.argv[2]
value = 1
with open(path, "rb") as handle:
    for chunk in iter(lambda: handle.read(8 * 1024 * 1024), b""):
        value = zlib.adler32(chunk, value)
actual = format(value & 0xFFFFFFFF, "08x")
print(f"    adler32 {actual} (expected {expected})")
if actual != expected:
    raise SystemExit("ERROR: checksum mismatch -- delete the file and retry")
PY

# ------------------------------------------------------------------ priors --
echo
echo "==> required theory priors"
missing=0
required=(
    "legacy/cms_jpsi_mumu_mg5_8tev_mixed_ptj5.hdf5"
    "cms_dymumu_mg5py8_ckkwl_8tev_inclusive_0j1j_fiducial_70_110_1M.hdf5"
)
for rel in "${required[@]}"; do
    if [[ -f "${DATA_ROOT}/${rel}" ]]; then
        printf '    present  %s\n' "${rel}"
    else
        printf '    MISSING  %s\n' "${rel}"
        missing=1
    fi
done

if [[ "${missing}" == "1" ]]; then
    cat <<EOF

Missing priors are not downloadable: they are generated by scripts/prior_build
and are gitignored. Copy them from the workstation (note that the transfer host
is access-hpc3.rcic.uci.edu and RCIC asks you to avoid rsync -a/-p):

  # on the Windows workstation, from the repository root:
  rsync -rltv --size-only data/legacy/ <UCInetID>@access-hpc3.rcic.uci.edu:${DATA_ROOT}/legacy/
  rsync -rltv --size-only data/cms_dymumu_mg5py8_ckkwl_8tev_inclusive_0j1j_fiducial_70_110_1M.hdf5 \\
      <UCInetID>@access-hpc3.rcic.uci.edu:${DATA_ROOT}/
  # or copy the whole tree once (about 2.4 GB excluding the ROOT file):
  rsync -rltv --exclude '${ROOT_NAME}' data/ <UCInetID>@access-hpc3.rcic.uci.edu:${DATA_ROOT}/

-rltv (not -a) preserves timestamps, which the region-cache identity check
uses, without copying ownership/permissions. See the runbook, section 4.
EOF
    exit 2
fi

echo
echo "==> data staging complete"
du -sh "${DATA_ROOT}"
