#!/usr/bin/env python
"""D3 cycle-weight probe: does a heavier per-event term move the honest-prior latent gauge?

Read-only. Compares the bounded probe ``Run_H_A2cycW5native`` (A2.4 arm,
``cycle_decoder_noise: native`` + frozen kernel, with the cycle weight scaled
x5) against two references over the **first 40 globals** of the 20/80/80
schedule:

* ``Run_H_A2frozen``   - beta = 1, cycle noise **zero** (the current A2
  deliverable; the D3 reference)
* ``Run_H_A2cycleNoise`` - beta = 1, cycle noise **native** (A2.4, refuted;
  stopped at global 45, so it supplies the matched beta=1 baseline for exactly
  the probe's noise regime)

The D3 gauge is the J/psi encoder latent mass KS on the honest (narrow) prior:
target 0.04, identity baseline 0.385, A2frozen 0.372-0.736 over stage 2.
Lower is better. Globals 1-20 are the deterministic stage-1 warmup (identical
schedule in all three arms, differing only in the cycle weight); globals 21-40
are the first 20 epochs of stage 2, where the noise regimes differ.

Nothing is trained; a JSON + markdown report is written into the probe's run
directory only.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
OUT_ROOT = REPO_ROOT / "outputs" / "cms_Joint"

# run dir -> (label, colour note for the report)
ARMS = [
    ("Run_H_A2cycW5native", "probe beta=5 native-cycle"),
    ("Run_H_A2frozen", "A2frozen beta=1 zero-cycle"),
    ("Run_H_A2cycleNoise", "A2.4 beta=1 native-cycle"),
]

WINDOW = 40


def load_rows(run: str) -> dict[int, dict]:
    path = OUT_ROOT / run / "history.json"
    if not path.exists():
        return {}
    rows = json.loads(path.read_text(encoding="utf-8"))
    out: dict[int, dict] = {}
    for r in rows:
        g = r.get("global_epoch")
        if g is None or g > WINDOW:
            continue
        jpsi = (r.get("region_validation") or {}).get("jpsi") or {}
        train = r.get("train") or {}
        out[g] = {
            "stage": r.get("stage"),
            "latent_mass_ks": jpsi.get("latent_mass_ks"),
            "latent_mass_ks_vs_identity": jpsi.get("latent_mass_ks_vs_identity"),
            "latent_identity_mass_ks": jpsi.get("latent_identity_mass_ks"),
            "selection": (r.get("joint_selection") or {}).get(
                "raw_worst_region_score"
            ),
            "cycle_loss": train.get("jpsi_x_loss"),
            "eval_loss": r.get("eval_loss"),
        }
    return out


def fmt(value, spec: str = ".3f") -> str:
    return "—" if value is None else format(value, spec)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", type=Path, default=None)
    args = ap.parse_args()

    data = {run: load_rows(run) for run, _ in ARMS}
    probe = data["Run_H_A2cycW5native"]
    out_dir = args.out or (OUT_ROOT / "Run_H_A2cycW5native" / "d3_compare")
    out_dir.mkdir(parents=True, exist_ok=True)

    # Reference values from memory.md Session 54 (A2frozen stage-2 trajectory).
    ref_gate = {
        "target_ks": 0.04,
        "identity_ks": 0.385,
        "a2frozen_stage2_g25_g30_g35_g40": [0.462, 0.445, 0.401, 0.360],
    }

    lines = [
        "# D3 cycle-weight probe — first 40 globals vs the beta=1 references",
        "",
        "*Read-only. Generated by `scripts_joint/d3_probe_compare.py`.*",
        "D3 gauge = J/psi encoder **latent mass KS** on the honest narrow prior",
        f"(target {ref_gate['target_ks']}, identity {ref_gate['identity_ks']}). "
        "Lower is better.",
        "",
        "## J/psi latent mass KS per global epoch",
        "",
        "| global | stage | probe beta=5 native | A2frozen beta=1 zero | A2.4 beta=1 native |",
        "|---|---|---|---|---|",
    ]
    globals_present = sorted(set().union(*[set(d) for d in data.values()]))
    for g in globals_present:
        stage = (probe.get(g, {}).get("stage") or "").replace(
            "runH_stage", "s"
        ).replace("_deterministic_warmup", "").replace("_stochastic_core", "")
        row = [str(g), stage or "—"]
        for run, _ in ARMS:
            row.append(fmt((data[run].get(g) or {}).get("latent_mass_ks")))
        lines.append("| " + " | ".join(row) + " |")

    lines += [
        "",
        "## Cycle term actually seen in training (jpsi_x_loss)",
        "",
        "The probe runs beta x5, so the *weighted* contribution is 5x this value;",
        "the value itself is the raw term, so it is directly comparable across arms.",
        "",
        "| global | probe beta=5 native | A2frozen beta=1 zero | A2.4 beta=1 native |",
        "|---|---|---|---|",
    ]
    for g in globals_present:
        row = [str(g)]
        for run, _ in ARMS:
            row.append(fmt((data[run].get(g) or {}).get("cycle_loss")))
        lines.append("| " + " | ".join(row) + " |")

    # Verdict against A2frozen over stage 2 (globals 21..40).
    stage2 = [g for g in globals_present if 21 <= g <= WINDOW]
    verdict = []
    for run, label in ARMS:
        vals = [
            (data[run].get(g) or {}).get("latent_mass_ks") for g in stage2
        ]
        vals = [v for v in vals if v is not None]
        if vals:
            verdict.append(
                {
                    "arm": run,
                    "label": label,
                    "stage2_globals": len(vals),
                    "ks_min": min(vals),
                    "ks_max": max(vals),
                    "ks_last": vals[-1],
                }
            )
    lines += ["", "## Stage-2 summary (globals 21-40)", ""]
    if verdict:
        lines += [
            "| arm | epochs | min latent KS | max latent KS | last |",
            "|---|---|---|---|---|",
        ]
        for v in verdict:
            lines.append(
                f"| {v['label']} | {v['stage2_globals']} | {v['ks_min']:.3f} | "
                f"{v['ks_max']:.3f} | {v['ks_last']:.3f} |"
            )
    else:
        lines.append("No stage-2 epochs recorded yet.")

    lines += [
        "",
        "## Gate",
        "",
        f"* D3 target: latent mass KS <= {ref_gate['target_ks']} (beats identity "
        f"{ref_gate['identity_ks']}); the best mass-only contraction of x reaches "
        "0.279, so anything above that is not unfolding.",
        f"* A2frozen stage-2 reference from memory.md Session 54: "
        f"{ref_gate['a2frozen_stage2_g25_g30_g35_g40']} at g25/g30/g35/g40.",
        "* Probe verdict: read whether beta x5 with a kernel-consistent cycle "
        "moves the KS toward the 0.04 target, or tracks the beta=1 arms.",
    ]
    (out_dir / "REPORT.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    payload = {
        "window": WINDOW,
        "reference_gate": ref_gate,
        "arms": [{"run": r, "label": l} for r, l in ARMS],
        "stage2_summary": verdict,
        "per_global": {
            run: {str(g): v for g, v in sorted(data[run].items())}
            for run, _ in ARMS
        },
    }
    (out_dir / "d3_compare.json").write_text(
        json.dumps(payload, indent=2, sort_keys=True), encoding="utf-8"
    )
    print(f"wrote {out_dir / 'REPORT.md'}")
    for v in verdict:
        print(
            f"  {v['label']:32s} stage2 n={v['stage2_globals']:<3} "
            f"min={v['ks_min']:.3f} last={v['ks_last']:.3f}"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
